apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: app-namespace
spec:
  template:
    spec:
      containers:
      - name: sample-app
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"