# Nginx ConfigMapベースのシンプルなIngress Controller
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        upstream app1 {
            server app1-service.default.svc.cluster.local:80;
        }
        upstream app2 {
            server app2-service.default.svc.cluster.local:80;
        }
        server {
            listen 80;
            location /app1 {
                proxy_pass http://app1/;
            }
            location /app2 {
                proxy_pass http://app2/;
            }
            location / {
                return 200 "Simple Ingress Controller Working!\nTry: /app1 or /app2";
                add_header Content-Type text/plain;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-ingress
  template:
    metadata:
      labels:
        app: simple-ingress
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          hostPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: simple-ingress-service
spec:
  selector:
    app: simple-ingress
  ports:
  - port: 80
    targetPort: 80
  type: NodePort