apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: app-namespace
spec:
  template:
    spec:
      containers:
      - name: sample-app
        env:
        - name: ENV
          value: "development"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"