apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

replicas:
  - name: sample-app
    count: 2

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: nginx
    newTag: 1.22