# シンプルなHTTPコントローラーとアプリケーション
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: web-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Kubernetes Ingress Demo</title>
        <style>
            body { font-family: Arial; text-align: center; margin-top: 50px; }
            .container { max-width: 800px; margin: 0 auto; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Kubernetes Ingress Controller Demo</h1>
            <p>This page shows that the Ingress Controller is working properly!</p>
            <hr>
            <h2>Test Paths:</h2>
            <ul>
                <li><a href="/app1">App1 - nginx demo</a></li>
                <li><a href="/app2">App2 - echo service</a></li>
            </ul>
        </div>
    </body>
    </html>
  app1.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>App1 - NGINX Demo</title>
    </head>
    <body style="text-align: center; margin-top: 50px;">
        <h1>App1 - NGINX Demo</h1>
        <p>This is App1 page (nginx)</p>
        <p><a href="/">Back to Home</a></p>
    </body>
    </html>
  app2.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>App2 - Echo Service</title>
    </head>
    <body style="text-align: center; margin-top: 50px;">
        <h1>App2 - Echo Service</h1>
        <p>This is App2 page (echo service)</p>
        <p><a href="/">Back to Home</a></p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
  - port: 80
    targetPort: 80
  type: NodePort