openapi: "3.0.1"
info:
  title: "test-synthetics-api"
  version: "v1"

paths:
  /:
    get:
      security:
        - api_key: []
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/${lambda_arn}/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"

components:
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"