name: TerraformChild

on:
  workflow_call:
    inputs:
      tf_dir:
        description: "The directory to run Terraform in"
        required: true
        type: string
    secrets:
      ACTIONS_ROLE_ARN:
        required: true

env:
  AWS_DEFAULT_REGION: "ap-northeast-1"

jobs:
  terraform:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup Python
        if: ${{ inputs.tf_dir == 'AWS/Resources/RAG/be/infra' }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Python deps を matrix で処理（be/infra のときだけ実行）
      - name: Install dependencies
        if: ${{ inputs.tf_dir == 'AWS/Resources/RAG/be/infra' }}
        run: |
          for dir in embed_doc vector_database answer_user_query; do
            echo "Installing dependencies for $dir"
            cd AWS/Resources/RAG/be/src/$dir
            python -m pip install --upgrade pip
            pip install \
              --platform manylinux2014_x86_64 \
              --implementation cp \
              --python-version 3.10 \
              --only-binary=:all: \
              --upgrade \
              -r requirements.txt -t ./layer/python
            cd -
          done

      - name: Exec Terraform fmt check
        run: terraform fmt -recursive -check
        working-directory: ${{ inputs.tf_dir }}

      - name: Exec Terraform init
        run: terraform init
        working-directory: ${{ inputs.tf_dir }}

      - name: Exec Terraform plan
        run: terraform plan -no-color
        working-directory: ${{ inputs.tf_dir }}
