name: TerraformCI
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  call-terraform:
    uses: ./.github/workflows/TerraformChild.yml # 子ワークフローを呼び出す
    with:
      tf_dir: ${{ matrix.TF_DIR }} # 子ワークフローにディレクトリを渡す
    secrets:
      ACTIONS_ROLE_ARN: ${{ secrets.ACTIONS_ROLE_ARN }}
    strategy:
      fail-fast: false
      matrix:
        TF_DIR:
          - AWS/Resources/RAG/fe/infra
          - AWS/Resources/RAG/be/infra

