name: TerraformChild
on:
  workflow_dispatch:
    inputs:
      tf_dir:
        description: "The directory to run Terraform in"
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.tf_dir }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Exec Terraform fmt check
        run: terraform fmt -recursive -check

      - name: Exec Terraform init
        run: terraform init

      - name: Exec Terraform plan
        run: terraform plan -no-color
