name: test-action
on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.1.2
  AWS_ROLE_ARN: arn:aws:iam::365084727525:role/test-GithubActionRole
  AWS_DEFAULT_REGION: ap-northeast-1
  AWS_PROFILE: GitHubActions

permissions:
  id-token: write
  contents: read

jobs:
  set-matrix:
    runs-on: ubuntu-20.04

    env:
      TF_ROOT_DIR: .

    outputs:
      dirs: ${{ steps.find-tfstate-dirs.outputs.dirs }}

    steps:
      - uses: actions/checkout@v2

      - name: Find tfstate dirs
        id: find-tfstate-dirs
        run: |
          dirs=$(find ${TF_ROOT_DIR} -type f -name '*.tf' -exec dirname {} \; | grep -v 'modules\|\.terraform' | sort | uniq | jq -R -s -c 'split("\n")[:-1]')
          echo $dirs # 確認用
          echo "::set-output name=dirs::${dirs}"

  terraform:
    # environmentはgithub上でsetting -> environmentの設定をしていない場合は不要
    # environment:
    #   name: <環境名>

    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        TF_DIR: ${{ fromJson(needs.set-matrix.outputs.dirs) }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.TF_DIR }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GithubActionRole

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Exec Terraform fmt check
        run: |
          terraform fmt -recursive -check

      - name: Exec Terraform init
        run: |
          pwd; terraform init

      - name: Exec Terraform plan
        run: |
          pwd
          echo $AWS_PROFILE
          export AWS_PROFILE=GitHubActions
          echo $AWS_PROFILE
          aws configure list
          terraform plan -no-color

      # - name: Exec Terraform apply
      #   uses: dflook/terraform-apply@v1
      #   with:
      #     path: policys
      #     auto_approve: true
