name: test-action
on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.1.2
  AWS_ROLE_ARN: arn:aws:iam::365084727525:role/test-GithubActionRole
  AWS_DEFAULT_REGION: ap-northeast-1

# permissions:
#   id-token: write
#   contents: read

jobs:
  directories:
    name: "Directory-changes"
    runs-on: ubuntu-latest
    steps:
      - uses: theappnest/terraform-monorepo-action@master
        id: directories
        with:
          ignore: |
            */*
            modules/*
            !Resources/**
      - run: echo ${{ steps.directories.outputs.modules }}
    outputs:
      dirs: ${{ steps.directories.outputs.modules }}

  terraform:
    # environmentはgithub上でsetting -> environmentの設定をしていない場合は不要
    # environment:
    #   name: <環境名>

    runs-on: ubuntu-latest
    needs: directories
    strategy:
      matrix:
        directories: ${{ fromJson(needs.directories.outputs.dirs) }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.directories }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Exec Terraform fmt check
        run: |
          terraform fmt -recursive -check

      - name: Exec Terraform init
        run: |
          pwd; terraform init

      - name: Exec Terraform plan
        run: |
          pwd; terraform plan -no-color

      # - name: Exec Terraform apply
      #   uses: dflook/terraform-apply@v1
      #   with:
      #     path: policys
      #     auto_approve: true
